
spring:
  profiles:
    include: secret
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: 'jdbc:mariadb://127.0.0.1:3306/${custom.dev_db.dbName}?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul'
    username: '${custom.dev_db.username}'
    password: '${custom.dev_db.password}'
  thymeleaf:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    root: INFO
    com.ll.mypill: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
